### ISSUE TITLE
검색 기능이 작동을 안 합니다.

### ISSUE THREAD

**Issue by AkiaCode** [microsoft/developerkorea#10]
![image](https://user-images.githubusercontent.com/71239005/103501851-d0c9a600-4e92-11eb-8a6b-cae65c9625b5.png)

![image](https://user-images.githubusercontent.com/71239005/103501863-db843b00-4e92-11eb-8c19-81f52cb15782.png)

**Comment by justinyoo** [comment]
한글 검색을 지원하지 않는 플러그인이라서 교체를 해야 할 것 같습니다

**Comment by AkiaCode** [comment]
![image](https://user-images.githubusercontent.com/71239005/103525837-42214d00-4ec3-11eb-85fc-abbc1f5d6712.png)

![image](https://user-images.githubusercontent.com/71239005/103525847-45b4d400-4ec3-11eb-9e1c-8f7feec313af.png)

좀 더 확인 해보니 1-2글자 때는 아예 검색이 안되고 3글자부터 검색을 하는 것 같습니다

**Comment by justinyoo** [comment]
수정했습니다. 이제 한글 세 글자 이상 치면 검색이 될 거예요

**Comment by AkiaCode** [comment]
> 수정했습니다. 이제 한글 세 글자 이상 치면 검색이 될 거예요

감사합니다 :)
