### ISSUE TITLE
feed가 404로 뜹니다

### ISSUE THREAD

**Issue by AkiaCode** [microsoft/developerkorea#11]
![image](https://user-images.githubusercontent.com/71239005/103501962-24d48a80-4e93-11eb-913a-d0592675c83f.png)

F5를 하니까 정상적으로 뜹니다.
![image](https://user-images.githubusercontent.com/71239005/103502000-3c137800-4e93-11eb-8146-a82fb0771233.png)

**Comment by justinyoo** [comment]
이 부분은 좀 더 확인해 보도록 하겠습니다. 제 쪽에서 재현이 안되는지라... ㅠ

**Comment by AkiaCode** [comment]
![image](https://user-images.githubusercontent.com/71239005/103525996-7b59bd00-4ec3-11eb-95ab-a8bca78ee717.png)


사파리에서도 동일한 현상이 나옵니다

**Comment by AkiaCode** [comment]
> ![image](https://user-images.githubusercontent.com/71239005/103525996-7b59bd00-4ec3-11eb-95ab-a8bca78ee717.png)
> 
> 
> 사파리에서도 동일한 현상이 나옵니다

iOS 14.0.1

**Comment by justinyoo** [comment]
우선은 메인에서 RSS 피드 링크를 빼는 쪽으로 처리해 두겠습니다. 플러그인 문제인지 아니면 깃헙 페이지 자체의 문제인지는 좀 더 봐야겠네요.

**Comment by AkiaCode** [comment]
> 우선은 메인에서 RSS 피드 링크를 빼는 쪽으로 처리해 두겠습니다. 플러그인 문제인지 아니면 깃헙 페이지 자체의 문제인지는 좀 더 봐야겠네요.

네넵, 알겠습니다

**Comment by justinyoo** [comment]
새창으로 열기로 하면 잘 열리는 것을 확인했습니다. 그에 따라 피드 관련 모든 링크를 바꿨구요, Feedly 같은 서비스에서 잘 채집이 되는 걸로 확인이 된 결과 이 이슈는 닫도록 하겠습니다.

**Comment by AkiaCode** [comment]
> 새창으로 열기로 하면 잘 열리는 것을 확인했습니다. 그에 따라 피드 관련 모든 링크를 바꿨구요, Feedly 같은 서비스에서 잘 채집이 되는 걸로 확인이 된 결과 이 이슈는 닫도록 하겠습니다.

아하, 새창으로 열면 잘 되는 거군요, 알려주셔서 감사합니다 :>
