### ISSUE TITLE
링크 교체를 해야 할 거 같습니다

### ISSUE THREAD

**Issue by AkiaCode** [microsoft/developerkorea#9]
![image](https://user-images.githubusercontent.com/71239005/103501730-6ca6e200-4e92-11eb-873d-0ed83d9dee9d.png)

![image](https://user-images.githubusercontent.com/71239005/103501741-77fa0d80-4e92-11eb-99da-ed04a47681dc.png)

**Comment by justinyoo** [comment]
확인해 보겠습니다!

**Comment by AkiaCode** [comment]
저가 확인해본 결과 blog 였던 폴더가 posts로 변경 되어서 사진이 안나오게 되었습니다

번경 전: https://github.com/devrel-kr/gridsome-starter-liebling/blob/main/content/**blog**/images/ingmar-hoogerhoud-lm91dJNPRS4-unsplash.jpg?raw=true

번경 후: https://github.com/devrel-kr/gridsome-starter-liebling/blob/main/content/**posts**/images/ingmar-hoogerhoud-lm91dJNPRS4-unsplash.jpg?raw=true

**Comment by justinyoo** [comment]
#13 PR을 통해 이슈를 해결했습니다. 기여해 주셔서 감사 드립니다!
